export const programmers = [
  {
    id: "bc4a07b97e7e28f0f7dfb3d293f04969",
    firstName: "Alexandr",
    lastName: "Hamabrdzumyan",
    phone: "",
    email: "alexanhambarcumyan@gmail.com",
    education: "Shushi Technology university",
    workExperience: "AIPC",
    trainings: "RELQ school",
    imagePath: "AlexandrHambardzumyan.jpg",
  },
  {
    id: "d624f7f999d82655ea866cf7e62d0f70",
    firstName: "Anahit",
    lastName: "Khechumyan",
    phone: "",
    email: "Khechumyan63@gmail.com",
    education: "Yerevan State University",
    workExperience: "School Principal-School N67 Bitschool",
    trainings: "RELQ",
    imagePath: "AnahitKhechumyan.jpg",
  },
  {
    id: "c23af019603e2dfbc2efc3017380e1d6",
    firstName: "Ani",
    lastName: "Antonyan",
    phone: "",
    email: "",
    education: "",
    workExperience: "",
    trainings: "RELQ",
    imagePath: "AniAntonyan.jpg",
  },
  {
    id: "98d55851aa21a694de834e243d20d3b2",
    firstName: "Anna",
    lastName: "Hayriyan",
    phone: "",
    email: "annhayriyan@gmail.com",
    education: "ASUE",
    workExperience: "Scott logistics",
    trainings: "RELQ",
    imagePath: "girl.png",
  },
  {
    id: "f6c29a09573da058ef676bbbc9926ec5",
    firstName: "Armenak",
    lastName: "Qocharyan",
    phone: "",
    email: "qocharyanarmenak@gmail.com",
    education: "Բարձրագույն զինվորական",
    workExperience: "ՀՀ ՊՆ",
    trainings: "Relq School",
    imagePath: "ArmenakQocharyan.jpg",
  },
  {
    id: "eb5390a89383441dd1cb397cc14d7034",
    firstName: "Arusyak",
    lastName: "Aghajanyan",
    phone: "",
    email: "aghajanyanarusyak@gmail.com",
    education: "YSUGU",
    workExperience: "InecoBank CJSC, Risk meneger",
    trainings:
      "BasicItCenter,UNDP Armenia Accelerator5,HTI Armenia C++ basic, SmartCode,Relq Technology",
    imagePath: "ArusyakAghajanyan.jpg",
  },
  {
    id: "94e2f5d4c28a0cc8d615e15d03ca2ebd",
    firstName: "Afina",
    lastName: "Panyan",
    phone: "",
    email: "",
    education: "",
    workExperience: "",
    trainings: "Relq",
    imagePath: "girl.png",
  },
  {
    id: "d89d63b6a084e295a0b9241bf4757b9e",
    firstName: "Babken",
    lastName: "Tadevosyan",
    phone: "",
    email: "",
    education: "",
    workExperience: "",
    trainings: "Relq",
    imagePath: "boy.png",
  },
  {
    id: "fd31908eccd95b47e6f3d9dffbcb275f",
    firstName: "Hasmik",
    lastName: "Gevorgyan",
    phone: "",
    email: "",
    education: "",
    workExperience: "",
    trainings: "Relq",
    imagePath: "HasmikGevorgyan.jpg",
  },
  {
    id: "edf8849d2fcc02deb053edf1080704fd",
    firstName: "Hermine",
    lastName: "Melkumyan",
    phone: "",
    email: "",
    education: "",
    workExperience: "",
    trainings: "Relq",
    imagePath: "HermineMelkumyan.jpg",
  },
  {
    id: "afd741d6621ae423c7de8c97dc76caa8",
    firstName: "Hermine",
    lastName: "Sahakyan",
    phone: "",
    email: "",
    education: "",
    workExperience: "",
    trainings: "Relq",
    imagePath: "girl.png",
  },
  {
    id: "d4f0550fdb7adb4ad358ecbcdd1b44d8",
    firstName: "Larine",
    lastName: "Danielyan",
    phone: "",
    email: "danielyanlari@gmail.com",
    education: "Economics and Menegment",
    workExperience: "Martuninsky district Medical Association",
    trainings: "Relq",
    imagePath: "LarineDanielyan.jpg",
  },
  {
    id: "c6282e7848e1fafeecf73b8973ecda76",
    firstName: "Liana",
    lastName: "Dashyan",
    phone: "",
    email: "dashyanlian@gmail.com",
    education: "YSU",
    workExperience: "GYU NGO",
    trainings: "Relq",
    imagePath: "girl.png",
  },
  {
    id: "f636db8e6bc66cb5cb16510a5d3d78e3",
    firstName: "Lusine",
    lastName: "Yeremyan",
    phone: "",
    email: "lusineer@gmail.com",
    education: "Economist",
    workExperience: "Municipality",
    trainings: "Relq, MIC",
    imagePath: "LusineYeremyan.jpg",
  },
  {
    id: "afb5cdfbd5f8a8a59ac319ebb2e7389f",
    firstName: "Lusine",
    lastName: "Petrosyan",
    phone: "",
    email: "plusine99@gmail.com",
    education: "Armenian State University faculty of Radiophysics",
    workExperience: "",
    trainings: "Relq",
    imagePath: "LusinePetrosyan.jpg",
  },
  {
    id: "b940aeb6fdaab981c14ad7343ef8991d",
    firstName: "Karen",
    lastName: "Darbinyan",
    phone: "",
    email: "kar31100@gmail.com",
    education: "YSU",
    workExperience: "alam asxarh",
    trainings: "RELQ",
    imagePath: "KarenDarbinyan.jpg",
  },
  {
    id: "acdce4326ad5823fea4f412fcc441da1",
    firstName: "Marat",
    lastName: "Harutyunyan",
    phone: "",
    email: "maratharutyunyan.mh.mh@gmail.com",
    education: "ASIPCS",
    workExperience: "EL Market",
    trainings: "Relq School",
    imagePath: "MaratHarutyunyan.jpg",
  },
  {
    id: "f009e9cb000f23a988b2462b748d401a",
    firstName: "Narek",
    lastName: "Tovmasyan",
    phone: "",
    email: "Narektom333@gmail.com",
    education: "ASUE",
    workExperience: "Ameria Bank",
    trainings: "Relq School",
    imagePath: "NarekTovmasyan.jpg",
  },
  {
    id: "dbe5a55a2c817e51b127e5278010ea51",
    firstName: "Seda",
    lastName: "Shahnazaryan",
    phone: "",
    email: "shahnazaryan.seda@mail.ru",
    education: "Higher Education:Historian",
    workExperience: "",
    trainings: "TechBoost4Women,RELQ technology school",
    imagePath: "SedaShahnazaryan.jpg",
  },
  {
    id: "d1a6ee330c6fe004970ffa4e7e3feec6",
    firstName: "Seryozha",
    lastName: "Asatryan",
    phone: "",
    email: "seryozha.asatryan02@gmail.com",
    education: "Economics",
    workExperience: "",
    trainings: "Relq School",
    imagePath: "SeryozhaAsatryan.jpg",
  },
  {
    id: "8859b83d27de7165893703b8cbc509a6",
    firstName: "Sevak",
    lastName: "Stepanyan",
    phone: "",
    email: "stepanyansevak9@gamil.com",
    education: "Economics and Menegment",
    workExperience: "",
    trainings: "Relq School",
    imagePath: "boy.png",
  },
  {
    id: "96140b3067164727be9d608f17e50775",
    firstName: "Silva",
    lastName: "Ohanyan",
    phone: "",
    email: "",
    education: "",
    workExperience: "",
    trainings: "Relq School",
    imagePath: "girl.png",
  },
  {
    id: "cf54e2f887bcb3aca09c41d50e302454",
    firstName: "Suren",
    lastName: "Galstyan",
    phone: "",
    email: "",
    education: "",
    workExperience: "",
    trainings: "Relq School",
    imagePath: "boy.png",
  },
  {
    id: "ac5e541f01dce8a3a1a17b806470a258",
    firstName: "Tigran",
    lastName: "Martirosyan",
    phone: "",
    email: "martirosyant01@mail.ru",
    education: "",
    workExperience: "",
    trainings: "Relq School",
    imagePath: "TigranMartirosyan.jpg",
  },
];
