export const xx = [
  {
    id: "b92e2d4cb7157265a56bb23975b0ac8a",
    firstName: "Alexandr",
    lastName: "Hamabrdzumyan",
    phone: "+37497705090",
    email: "alexanhambarcumyan@gmail.com",
    education: "Shushi Technology university",
    workExperience: "AIPC",
    trainings: "RELQ school",
    imagePath: "./img/AlexandrHambardzumyan.jpg",
  },
  {
    id: "9ef64007dc04570be29393bfe5704164",
    firstName: "Anahit",
    lastName: "Khechumyan",
    phone: "+37444148000",
    email: "Khechumyan63@gmail.com",
    education: "Yerevan State University",
    workExperience: "School Principal-School N67 Bitschool",
    trainings: "RELQ",
    imagePath: "./img/AnahitKhechumyan.jpg",
  },
  {
    id: "8d1a272ce134dae2a72baac82da790d3",
    firstName: "Ani",
    lastName: "Antonyan",
    phone: "",
    email: "",
    education: "",
    workExperience: "",
    trainings: "RELQ",
    imagePath: "./img/AniAntonyan.jpg",
  },
  {
    id: "d6493ab8fe05b315d8a1312e7fb11dbe",
    firstName: "Anna",
    lastName: "Hayriyan",
    phone: "+37498144450",
    email: "annhayriyan@gmail.com",
    education: "ASUE",
    workExperience: "Scott logistics",
    trainings: "RELQ",
    imagePath: "./img/girl.png",
  },
  {
    id: "dc1040c571a450d09db73f32c5f21b72",
    firstName: "Armenak",
    lastName: "Qocharyan",
    phone: " +37494902171",
    email: "qocharyanarmenak@gmail.com",
    education: "Բարձրագույն զինվորական",
    workExperience: "ՀՀ ՊՆ",
    trainings: "Relq School",
    imagePath: "./img/ArmenakQocharyan.jpg",
  },
  {
    id: "c4f079f3e1d4997eb2a62b2c3e51342b",
    firstName: "Arusyak",
    lastName: "Aghajanyan",
    phone: "+37455900155",
    email: "aghajanyanarusyak@gmail.com",
    education: "YSUGU",
    workExperience: "InecoBank CJSC, Risk meneger",
    trainings:"BasicItCenter,UNDP Armenia Accelerator5,HTI Armenia C++ basic, SmartCode,Relq Technology",
    imagePath: "./img/ArusyakAghajanyan.jpg",
  },
  {
    id: "e4d337d2dff130e0d692c59a1efe1c95",
    firstName: "Afina",
    lastName: "Panyan",
    phone: "",
    email: "",
    education: "",
    workExperience: "",
    trainings: "Relq",
    imagePath: "./img/girl.png",
  },
  {
    id: "d0a54c9223878eea81a954f761eeda2f",
    firstName: "Babken",
    lastName: "Tadevosyan",
    phone: "",
    email: "",
    education: "",
    workExperience: "",
    trainings: "Relq",
    imagePath: "./img/boy.png",
  },
  {
    id: "faabf15e448c60e0e2b8dc6be426b2d9",
    firstName: "Hasmik",
    lastName: "Gevorgyan",
    phone: "+37499463623",
    email: "gevorgyan.icml@gmail.com",
    education: "YEREVAN STATE COLLEGE OF INFORMATICS",
    workExperience: "Mon Amie Flowers & Design boutique",
    trainings: "Relq",
    imagePath: "./img/HasmikGevorgyan.jpg",
  },
  {
    id: "ed694a2754765b80edcb7cb12c2dc2d8",
    firstName: "Hermine",
    lastName: "Melkumyan",
    phone: "",
    email: "",
    education: "",
    workExperience: "",
    trainings: "Relq",
    imagePath: "./img/HermineMelkumyan.jpg",
  },
  {
    id: "cd145e5bc443e392a5ebb6fdc3ff2768",
    firstName: "Hermine",
    lastName: "Sahakyan",
    phone: "",
    email: "",
    education: "",
    workExperience: "",
    trainings: "Relq",
    imagePath: "./img/girl.png",
  },
  {
    id: "ff1a47edca922f8cea7d68e6f24258fe",
    firstName: "Larine",
    lastName: "Danielyan",
    phone: " +37497759599",
    email: "danielyanlari@gmail.com",
    education: "Economics and Menegment",
    workExperience: "Martuninsky district Medical Association",
    trainings: "Relq",
    imagePath: "./img/LarineDanielyan.jpg",
  },
  {
    id: "d7ef716d4da45aa39acb8f061961f828",
    firstName: "Liana",
    lastName: "Dashyan",
    phone: "+37491555374",
    email: "dashyanlian@gmail.com",
    education: "YSU",
    workExperience: "GYU NGO",
    trainings: "Relq",
    imagePath: "./img/girl.png",
  },
  {
    id: "eca9fefad75fcf20980ef81437d93704",
    firstName: "Lusine",
    lastName: "Yeremyan",
    phone: " +3744318183",
    email: "lusineer@gmail.com",
    education: "Economist",
    workExperience: "Municipality",
    trainings: "Relq, MIC",
    imagePath: "./img/LusineYeremyan.jpg",
  },
  {
    id: "9e4495d716487260ab5d0bd44f6daa3a",
    firstName: "Lusine",
    lastName: "Petrosyan",
    phone: "+37493322902",
    email: "plusine99@gmail.com",
    education: "Armenian State University faculty of Radiophysics",
    workExperience: "",
    trainings: "Relq",
    imagePath: "./img/LusinePetrosyan.jpg",
  },
  {
    id: "880d764b73cac2068b0e90b604eaaa0d",
    firstName: "Karen",
    lastName: "Darbinyan",
    phone: "+37498156247",
    email: "kar31100@gmail.com",
    education: "YSU",
    workExperience: "alam asxarh",
    trainings: "RELQ",
    imagePath: "./img/KarenDarbinyan.jpg",
  },
  {
    id: "8c06f4f71d9a2c7c9a831b4695121924",
    firstName: "Marat",
    lastName: "Harutyunyan",
    phone: " +37444055150",
    email: "maratharutyunyan.mh.mh@gmail.com",
    education: "ASIPCS",
    workExperience: "EL Market",
    trainings: "Relq School",
    imagePath: "./img/MaratHarutyunyan.jpg",
  },
  {
    id: "d080a47db81f67b6bba20ebeab17825f",
    firstName: "Narek",
    lastName: "Tovmasyan",
    phone: "+37494276700",
    email: "Narektom333@gmail.com",
    education: "ASUE",
    workExperience: "Ameria Bank",
    trainings: "Relq School",
    imagePath: "./img/NarekTovmasyan.jpg",
  },
  {
    id: "a66dfecd40c68946ebe27118e7e703c4",
    firstName: "Seda",
    lastName: "Shahnazaryan",
    phone: "+37498313871",
    email: "shahnazaryan.seda@mail.ru",
    education: "Higher Education:Historian",
    workExperience: "15 years",
    trainings: "TechBoost4Women,RELQ technology school",
    imagePath: "./img/SedaShahnazaryan.jpg",
  },
  {
    id: "839d7f30fb3428c3e8cf7d3f7971568c",
    firstName: "Seryozha",
    lastName: "Asatryan",
    phone: "+37494246880",
    email: "seryozha.asatryan02@gmail.com",
    education: "Economics",
    workExperience: "",
    trainings: "Relq School",
    imagePath: "./img/SeryozhaAsatryan.jpg",
  },
  {
    id: "c7690119dd6d7d90b72f9e41c46f2ac5",
    firstName: "Sevak",
    lastName: "Stepanyan",
    phone: "+37477121696",
    email: "stepanyansevak9@gamil.com",
    education: "Economics and Menegment",
    workExperience: "2 Years",
    trainings: "Relq School",
    imagePath: "./img/boy.png",
  },
  {
    id: "e10ba4caa4bfdcb7efd3aa12404f15aa",
    firstName: "Silva",
    lastName: "Ohanyan",
    phone: "",
    email: "",
    education: "",
    workExperience: "",
    trainings: "Relq School",
    imagePath: "./img/girl.png",
  },
  {
    id: "ea770554456342ebc0830deea6785755",
    firstName: "Suren",
    lastName: "Galstyan",
    phone: "",
    email: "",
    education: "",
    workExperience: "",
    trainings: "Relq School",
    imagePath: "./img/boy.png",
  },
  {
    id: "c1f6af3eeb674ce3e2107b32ab399cce",
    firstName: "Tigran",
    lastName: "Martirosyan",
    phone: "+37477151868",
    email: "martirosyant01@mail.ru",
    education: "",
    workExperience: "",
    trainings: "Relq School",
    imagePath: "./img/TigranMartirosyan.jpg",
  },
];
